# Project-wide Gradle settings.
# https://developer.android.com/r/tools/gradle-multi-project-decoupled-projects
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# org.gradle.parallel=true

android.useAndroidX=true
android.nonTransitiveRClass=true

# Mejora el rendimiento de importación en proyectos grandes (AGP 8.7+).
android.dependency.excludeLibraryComponentsFromConstraints=true
